# Generated by Django 3.2 on 2021-04-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picuploading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='User',
            new_name='user',
        ),
    ]
