# Generated by Django 3.2 on 2021-04-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picuploading', '0002_rename_user_profilepic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('price', models.FloatField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirydate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picuploading.product')),
            ],
        ),
    ]
