# Generated by Django 3.2 on 2021-04-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picuploading', '0003_product_product1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='picuploading.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product1',
            name='expirydate',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
